name: pbpl204
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3
  - jupyterlab                      # necessary to run notebooks
  - pandoc                          # necessary to compile the paper
  - pandoc-crossref                 # necessary to compile the paper
  - numba==0.48
  - geopandas >=0.7
  - pandas >=1
  - scikit-learn
  - scipy
  - pysal >=2.2
  - descartes
  - pandana
  - geosnap >=0.3
  - segregation
  - pip
  - pip:
    - pandoc-include                 # necessary to compile the paper
    - pandoc-latex-admonition        # necessary to compile the paper
